### ISSUE TITLE
Practica de Hilos en Consola

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/practica-de-hilos-FedericoVictorianoSierra#2]
El estudiante debe realizar ejercicios de la utilización de hilos con C#

**Comment by FedericoVictorianoSierra** [comment]
[Practica 6 (Federico Victoriano Sierra(4US)).pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-FedericoVictorianoSierra/files/8420926/Practica.6.Federico.Victoriano.Sierra.4US.pdf)

**Comment by FedericoVictorianoSierra** [comment]
[Practica 6 (Federico Victoriano Sierra(4US)).pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-FedericoVictorianoSierra/files/8438876/Practica.6.Federico.Victoriano.Sierra.4US.pdf)

**Comment by JudithReynaCS** [comment]
CALIFICACION:20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
